### ISSUE TITLE
Control what parts of user info get serialized 

### ISSUE THREAD

**Issue by wgorder** [spring-projects/spring-session#100]
I have a quick question I am trying to get an example going with spring-cloud utilizing spring session.
https://github.com/wgorder/spring-cloud-examples

I have multiple services and the auth-server handles the authentication and apparently serializes the entire user details service as when the api-gateway application tries to deserialize it I get this.

I am already duplicating the user entities across the 2 applications but I don't feel I should need to duplicate the user details stuff as well.  Is there a way I can exercise more control as to what gets put on the session here?  You can see the code in question in these 2 projects:

https://github.com/wgorder/auth-server
https://github.com/wgorder/api-gateway

```
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: com.acme.demo.auth.user.AcmeUserDetailsService$AcmeUserDetails
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:41)
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:296)
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:257)
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:227)
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:101)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:214)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:201)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:118)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:190)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
	at org.springframework.security.web.context.HttpSessionSecurityContextRepository.loadContext(HttpSessionSecurityContextRepository.java:85)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:111)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: com.acme.demo.auth.user.AcmeUserDetailsService$AcmeUserDetails
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:64)
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:34)
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:39)
	... 50 common frames omitted
Caused by: org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: com.acme.demo.auth.user.AcmeUserDetailsService$AcmeUserDetails
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:44)
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:59)
	... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.acme.demo.auth.user.AcmeUserDetailsService$AcmeUserDetails
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:41)
	... 53 common frames omitted
```

**Comment by wgorder** [comment]
Ill probably just end up splitting it out into its own class instead of a nested one, and duplicating it.  A shared lib might be appropriate here but not feasible for a demo as I am not publishing artifacts anywhere.

**Comment by wgorder** [comment]
Ill just close this.  I don't think there is away around duplicating the objects if using jackson to deserialize.  Of course adding a deserialization strategy that did not require pre-existing classes like groovy for example would be an interesting idea.

**Comment by jjparsons** [comment]
@wgorder - what was your solution for this Spring Session deserialization issue? Using Microservices over here as well and don't want to use shared libraries at the domain level....

**Comment by abruzzi** [comment]
@jjparsons - I got a same issue and wondering if you have solved it? Duplicate the domain object is not a good idea by any means. @wgorder

**Comment by jjparsons** [comment]
@wgorder I ended up switching to OAuth 2.0. You can ditch basic and sessions and transition directly into JWT tokens that encapsulate 3rd party identity provider information while providing a centralized user service to handle data proprietary to your platform. See the Spring Cloud Security project for more information such a OAuth SSO, resource services, clients etc. Note, this will effect all of your components and clients.

**Comment by wgorder** [comment]
@abruzzi @jjparsons   I switched to Oauth2 as well.  I actually don't bother with JWT as I had the requirement of being able to revoke tokens which required the need of a token store.

**Comment by abruzzi** [comment]
@jjparsons @wgorder Thanks for replying, I think that's a right way to go. Another thing I noticed is that if I deploy the individual services in docker container(and don't public the port to host), then I only need to do the A&A in API gateway, say, `zuul`, and there is no need to using `Redis` for replica. 

The individual services behind the gateway should be safe enough since no one can actually direct access them except the API gateway.

**Comment by mdaftabsmu** [comment]
Hi sir,
I am facing same problem , How to fix it ??
org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: in.cashify.redis.data.object.User
	org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:43)
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:58)
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:1)
	org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:40)
	org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:212)
	org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:52)
	in.cashify.redis.data.repositry.UserRepository.get(UserRepository.java:33)
	in.cashify.redis.RedisTest.main(RedisTest.java:26)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:94)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by mdaftabsmu** [comment]
full stack trace 

org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: in.cashify.redis.data.object.User
	org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:42)
	org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:212)
	org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:52)
	in.cashify.redis.data.repositry.UserRepository.get(UserRepository.java:33)
	in.cashify.redis.RedisTest.main(RedisTest.java:26)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:94)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: in.cashify.redis.data.object.User
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:61)
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:1)
	org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:40)
	org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:212)
	org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:52)
	in.cashify.redis.data.repositry.UserRepository.get(UserRepository.java:33)
	in.cashify.redis.RedisTest.main(RedisTest.java:26)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:94)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: in.cashify.redis.data.object.User
	org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:43)
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:58)
	org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:1)
	org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:40)
	org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:212)
	org.springframework.data.redis.core.DefaultHashOperations.get(DefaultHashOperations.java:52)
	in.cashify.redis.data.repositry.UserRepository.get(UserRepository.java:33)
	in.cashify.redis.RedisTest.main(RedisTest.java:26)
	org.apache.jsp.index_jsp._jspService(index_jsp.java:94)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

**Comment by jjparsons** [comment]
Spring Session doesn't work well in this context for Microservice
authentication using basic authentication. Couldn't resolve so I switched
to OAuth 2.0 which was a better decision overall. If it's not too late in
your development I would recommend. Auth0 is a great OAuth provider as well.
