### ISSUE TITLE
jdbc session and spring boot autoconfigure: java.lang.ClassNotFoundException: org.springframework.session.hazelcast.HazelcastFlushMode

### ISSUE THREAD

**Issue by svzubarev** [spring-projects/spring-session#1021]
I have spring boot 1.5.3 
spring boot autoconfigure 1.5.3.
spring-session 2.0.2

in application.properties:
`spring.session.store-type="jdbc"`

datasource configured

when container starting i get exception:
`Caused by: java.lang.NoClassDefFoundError: org/springframework/session/hazelcast/HazelcastFlushMode
	at org.springframework.boot.autoconfigure.session.SessionProperties$Hazelcast.<init>(SessionProperties.java:99) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.autoconfigure.session.SessionProperties.<init>(SessionProperties.java:43) ~[spring-boot-autoconfigure-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 50 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.session.hazelcast.HazelcastFlushMode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_144]
	... 57 common frames omitted`

in packed jar file no com.hazelcast.* jars.
I found a reference to org.springframework.session.hazelcast.HazelcastFlushMode in spring-boot-autoconfigure jar in META-INF/spring-configuration-metadata.json:
`"name":"spring.session.hazelcast.flush-mode"
"type":"org.springframework.session.hazelcast.HazelcastFlushMode"`

I found a workaround:
1) in application.properties add:
`spring.autoconfigure.exclude = "org.springframework.boot.autoconfigure.session.SessionAutoConfiguration"`
2) in configuration class add annotation @EnableJdbcHttpSession

but is there any more clear way to use jdbc session?

**Comment by vpavic** [comment]
Spring Boot 1.5 is provides dependency management and auto-configuration support for Spring Session 1.3 while Spring Boot 2.0 picks up Spring Session 2.0.

Due to the changes done in Spring Session 2.0, Spring Boot 1.5 auto-configuration is not compatible with them so the only way to make it work is to disable it, like you did with `spring.autoconfigure.exclude`.

Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
