### ISSUE TITLE
NullPointerException after invalidating session

### ISSUE THREAD

**Issue by matthews614** [spring-projects/spring-session#1076]
I upgraded my application from Spring Boot 2.0.1 and Hazelcast 3.8.5 to Spring Boot 2.0.2 and Hazelcast 3.9.4. After doing so, I notice a NullPointerException when logging out.

I am using Spring Security and have a org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler configured to invalidate the HttpSession after logout.  During a logout, Spring Session is failing with this stack trace:

```
java.lang.NullPointerException: null
	at org.springframework.session.hazelcast.HazelcastSessionRepository$SessionUpdateEntryProcessor.process(HazelcastSessionRepository.java:455) ~[spring-session-hazelcast-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:335) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:194) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:179) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.operation.EntryOperation.runVanilla(EntryOperation.java:395) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.operation.EntryOperation.run(EntryOperation.java:177) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) ~[hazelcast-3.9.4.jar:3.9.4]
	at ------ submitted from ------.(Unknown Source) ~[na:na]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeOnKeyInternal(MapProxySupport.java:1073) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKeyInternal(MapProxyImpl.java:106) ~[hazelcast-3.9.4.jar:3.9.4]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKey(MapProxyImpl.java:674) ~[hazelcast-3.9.4.jar:3.9.4]
	at org.springframework.session.hazelcast.HazelcastSessionRepository.save(HazelcastSessionRepository.java:236) ~[spring-session-hazelcast-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.hazelcast.HazelcastSessionRepository.save(HazelcastSessionRepository.java:110) ~[spring-session-hazelcast-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.saveSession(SessionRepositoryFilter.java:377) ~[spring-session-core-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:233) ~[spring-session-core-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:197) ~[spring-session-core-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:150) ~[spring-session-core-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81) ~[spring-session-core-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:472) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:349) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
``

My guess is that the spring-session is attempting to update a session that has been invalidated.

**Comment by vpavic** [comment]
Thanks for the report @matthews614. This is a regression caused by #1048.

**Comment by vpavic** [comment]
This was fixed in 6d02790. Fresh `2.0.4-BUILD-SNAPSHOT` should we available in around half an hour, I'd appreciate if you could give it a spin.

**Comment by matthews614** [comment]
Tested it out and it looks good on our end.

**Comment by vpavic** [comment]
Hi @Koizumi85 - sorry for the late reasponse, the `2.0.4.RELEASE` was released yesterday. In general, you should find this information on project's [milestones page](https://github.com/spring-projects/spring-session/milestones).
