### ISSUE TITLE
Use default spring session when redis is unavailable

### ISSUE THREAD

**Issue by Shashank1801** [spring-projects/spring-session#1102]
Hi all,

**Context:** I am trying to use the spring's redis session to save session across multiple tomcats on cloud. But there are some environments where redis will not be available. I want to configure a way to allow my application to go back to default implementation depending on the environment at runtime. 

I am not able to figure the correct way to revert to default spring session configuration when redis is not available in my environment. 

I am using 
```
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session-data-redis</artifactId>
    <version>2.0.4.RELEASE</version>
 </dependency>
```
I am able to use the redis session (with its default configuration) when I extended a class as follows:
```
public class RedisHttpSessionApplicationInitializer extends AbstractHttpSessionApplicationInitializer {

}
```

I tried using the constructor of my `RedisHttpSessionApplicationInitializer` to load the `SpringHttpSessionConfiguration` instead when redis is not available and followed the docs at 
[SpringHttpSessionConfiguration](https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/config/annotation/web/http/SpringHttpSessionConfiguration.html ), and, [EnableSpringHttpSession](https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/config/annotation/web/http/EnableSpringHttpSession.html). 

So I made some changes as follows:
```

public class RedisHttpSessionApplicationInitializer extends AbstractHttpSessionApplicationInitializer {
    public RedisHttpSessionApplicationInitializer(){
        super(SpringHttpSessionConfiguration.class);
    }

}

```
and
```
    @Bean
    public SessionRepository<MapSession> sessionRepository() {
        return new MapSessionRepository(new HashMap<>());
    }

```

I am still getting error as follows:
```
ERROR 921  [Thread 19] org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springSessionRepositoryFilter' defined in org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.session.SessionRepository<?>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:458)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1249)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1098)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.
```

Could you suggest me to try anything for my use case. Also, please let me know if you need more information from me.

**Comment by Shashank1801** [comment]
Closing the thread as it was just a question not an issue.
