### ISSUE TITLE
Null Pointer on RedisMessageListenerContainer 

### ISSUE THREAD

**Issue by shubhendujain** [spring-projects/spring-session#1340]
Exception in thread "springSessionRedisSubscriptionExecutor" java.lang.NullPointerException
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask$PatternSubscriptionTask.run(RedisMessageListenerContainer.java:705)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vpavic** [comment]
@shubhendujain Can you provide more details about your application and how to reproduce the problem? A sample application that reproduces the problem would be ideal.

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please comment back if you can provide more details and we can re-open the issue.
