### ISSUE TITLE
CockroackDB - retry txn (RETRY_WRITE_TOO_OLD)

### ISSUE THREAD

**Issue by chriswhite199** [spring-projects/spring-session#1494]
Odd exception observed when using jdbc session (2.1.7) with Cockroach DB (v19.1.0). The session was created without issue (manually selecting the session and attribute tables show data), but the log files are showing the following exception for each subsequent request:

```
2019-08-25 22:45:47.016 ERROR 64808 --- [1-auto-1-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context wit
h path [/security] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Unable to commit against JDBC Conn
ection; nested exception is org.hibernate.TransactionException: Unable to commit against JDBC Connection] with root cause

org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD): "sql tx
n" id=07d19509 key=/Table/282/1/"6762b598-0ea3-44f9-8752-d6183b6385d5"/0 rw=true pri=0.00481019 stat=PENDING epo=0 ts=1566798346.945522000,1 orig=1566798346.92630990
0,0 max=1566798346.926309900,0 wto=true seq=4
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:777) ~[postgresql-42.2.5.jar:42.2.5]
        at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:361) ~[HikariCP-3.2.0.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java) ~[HikariCP-3.2.0.jar:na]
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:81) ~[hibernate-core-5.3.10.Fin
al.jar:5.3.10.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocal
TransactionCoordinatorImpl.java:272) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104) ~[hibernate-core-5.3.10.Final.jar:5.3.10.Final]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:532) ~[spring-orm-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746) ~[spring-tx-5.1.8.RE
LEASE.jar:5.1.8.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714) ~[spring-tx-5.1.8.RELEASE.j
ar:5.1.8.RELEASE]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:152) ~[spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:421) ~[spring-session-jdbc-2.1.7.RELEASE.jar:2.
1.7.RELEASE]
        at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:135) ~[spring-session-jdbc-2.1.7.RELEASE.jar:2.
1.7.RELEASE]
        at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:240) ~[spring-sess
ion-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
        at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:201) ~[spring-session
-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
        at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryResponseWrapper.onResponseCommitted(SessionRepositoryFilter.java:189) ~[spri
ng-session-core-2.1.7.RELEASE.jar:2.1.7.RELEASE]
        at org.springframework.session.web.http.OnCommittedResponseWrapper.doOnResponseCommitted(OnCommittedResponseWrapper.java:227) ~[spring-session-core-2.1.7.REL
EASE.jar:2.1.7.RELEASE]
        at org.springframework.session.web.http.OnCommittedResponseWrapper.checkContentLength(OnCommittedResponseWrapper.java:217) ~[spring-session-core-2.1.7.RELEAS
E.jar:2.1.7.RELEASE]
        at org.springframework.session.web.http.OnCommittedResponseWrapper.access$200(OnCommittedResponseWrapper.java:38) ~[spring-session-core-2.1.7.RELEASE.jar:2.1
.7.RELEASE]
```

**Comment by vpavic** [comment]
Could you provide a sample for us that reproduces this problem? I'm afraid I don't have any first hand experience with CockroachDB.

**Comment by vpavic** [comment]
I can now see that there's a Docker image available for [CockroachDB](https://hub.docker.com/r/cockroachdb/cockroach/). I'll try to give our integration tests a spin against that.

**Comment by vpavic** [comment]
I've tried running our integration tests against Testcontainers' newly introduced support for CockroachDB (see testcontainers/testcontainers-java#499) and everything works so I don't see this being Spring Session related issue, even with us not officially supporting CockroachDB.

Therefore I'm closing this as invalid, but feel free to post back with a sample that would point to a problem with Spring Session's JDBC session repository.

**Comment by chriswhite199** [comment]
@vpavic - thanks for looking into this. I'll see if i can reproduce but as additional information that may be pertinent - in my current setup i'm using Spring Security SAML / SSO so i'm not sure if that's part of the issue.

**Comment by Sebastiano84** [comment]
HI guys,

I have the exact same error:


org.springframework.orm.jpa.JpaSystemException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD): "sql txn" id=0731e2a4 key=/Table/134/1/"\xa7p\xa2}\x89\x92N?\x87.\xb1\t'\xf5\xa2"/0 rw=true pri=0.04430995 stat=PENDING epo=0 ts=1580384623.223516585,1 orig=1580384623.047721123,0 max=1580384623.047721123,0 wto=true seq=2; nested exception is javax.persistence.PersistenceException: org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD): "sql txn" id=0731e2a4 key=/Table/134/1/"\xa7p\xa2}\x89\x92N?\x87.\xb1\t'\xf5\xa2"/0 rw=true pri=0.04430995 stat=PENDING epo=0 ts=1580384623.223516585,1 orig=1580384623.047721123,0 max=1580384623.047721123,0 wto=true seq=2
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:418)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:246)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy104.save(Unknown Source)

**Comment by gschaefer3** [comment]
Hi all,

I'm facing the same error (RETRY_WRITE_TOO_OLD) in a Spring app.  Are there recommendations how to resolve/work around this CockroachDB transaction issue?

Thanks!
