### ISSUE TITLE
when I user redis cluster, cleanupExpiredSessions Could not get a resource from the pool

### ISSUE THREAD

**Issue by lijunyong** [spring-projects/spring-session#2083]
```
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.2.13.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
```
@Slf4j
@Configuration
@EnableRedisHttpSession
public class RedisConfig {


    //缓存管理器
    @Bean
    public CacheManager  cacheManager(RedisConnectionFactory connectionFactory) {
        //设置缓存过期时间
        RedisCacheConfiguration redisCacheConfiguration = RedisCacheConfiguration.defaultCacheConfig()
                .entryTtl(Duration.ofMillis(10000));

        RedisCacheManager redisCacheManager =  RedisCacheManager.builder(RedisCacheWriter.nonLockingRedisCacheWriter(connectionFactory))
                .cacheDefaults(redisCacheConfiguration)
                .build();
        return redisCacheManager;
    }

    @Bean
    @ConfigurationProperties(prefix = "spring.redis.jedis.pool")
    public JedisPoolConfig jedisPoolConfig(){
        return new JedisPoolConfig();
    }

//    @Bean
//    @ConfigurationProperties(prefix = "spring.redis")
//    public RedisStandaloneConfiguration redisStandaloneConfiguration(){
//        return new RedisStandaloneConfiguration();
//    }

    @Bean
    public RedisClusterConfiguration redisClusterConfiguration(RedisProperties redisProperties){
        RedisClusterConfiguration redisClusterConfiguration
                = new RedisClusterConfiguration(redisProperties.getCluster().getNodes());
        redisClusterConfiguration.setMaxRedirects(redisProperties.getCluster().getMaxRedirects());
        log.info("cluster node : {}", redisProperties.getCluster().getNodes());
        return  redisClusterConfiguration;
    }


    @Bean
    public JedisConnectionFactory redisConnectionFactory(JedisPoolConfig jedisPoolConfig,  RedisClusterConfiguration redisClusterConfiguration) {
        JedisClientConfiguration.JedisClientConfigurationBuilder jpcf =  JedisClientConfiguration.builder();
        JedisClientConfiguration jedisClientConfiguration = jpcf.usePooling().poolConfig(jedisPoolConfig).build();
        return new JedisConnectionFactory(redisClusterConfiguration, jedisClientConfiguration);
    }

    @Bean
    public RedisTemplate<String, String> redisTemplate(RedisConnectionFactory factory){
        StringRedisTemplate template = new StringRedisTemplate(factory);
        setSerializer(template);
        template.afterPropertiesSet();
        return template;
    }

    private void setSerializer(StringRedisTemplate template){
        Jackson2JsonRedisSerializer jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer(Object.class);
        ObjectMapper om = new ObjectMapper();
        om.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);
        om.activateDefaultTyping(LaissezFaireSubTypeValidator.instance,ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);
        jackson2JsonRedisSerializer.setObjectMapper(om);
        template.setValueSerializer(jackson2JsonRedisSerializer);
    }
}
```
```
spring:
  redis:
    cluster:
      nodes: 10.114.10.2:22408,10.114.10.2:22409,10.114.10.3:22408,10.114.10.3:22409,10.114.10.4:22408,10.114.10.4:22409
      max-redirects: 5
    jedis:
      pool:
        max-total: 20
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 5
        test-on-create: false
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
    timeout: 30000
```
Exception
```
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:204)
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:45)
        at redis.clients.jedis.Protocol.process(Protocol.java:217)
        at redis.clients.jedis.Protocol.read(Protocol.java:283)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:377)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:314)
        at redis.clients.jedis.Connection.authext(Connection.java:434)
        at redis.clients.jedis.Connection.connect(Connection.java:247)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:317)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:2143)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:163)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:314)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:124)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:101)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:70)
        at redis.clients.jedis.BinaryJedisCluster.exists(BinaryJedisCluster.java:177)
        at org.springframework.data.redis.connection.jedis.JedisClusterKeyCommands.exists(JedisClusterKeyCommands.java:561)
        at org.springframework.data.redis.connection.RedisKeyCommands.exists(RedisKeyCommands.java:48)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
        at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.touch(RedisSessionExpirationPolicy.java:144)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:133)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.cleanupExpiredSessions(RedisIndexedSessionRepository.java:407)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:373)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:314)
        at redis.clients.jedis.Connection.authext(Connection.java:434)
        at redis.clients.jedis.Connection.connect(Connection.java:247)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:317)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:2143)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:163)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:314)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:124)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:101)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:70)
        at redis.clients.jedis.BinaryJedisCluster.exists(BinaryJedisCluster.java:177)
        at org.springframework.data.redis.connection.jedis.JedisClusterKeyCommands.exists(JedisClusterKeyCommands.java:561)
        at org.springframework.data.redis.connection.RedisKeyCommands.exists(RedisKeyCommands.java:48)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
        at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.touch(RedisSessionExpirationPolicy.java:144)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:133)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.cleanupExpiredSessions(RedisIndexedSessionRepository.java:407)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:373)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:314)
        at redis.clients.jedis.Connection.authext(Connection.java:434)
        at redis.clients.jedis.Connection.connect(Connection.java:247)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:317)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:2143)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:163)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:314)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:124)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:101)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:70)
        at redis.clients.jedis.BinaryJedisCluster.exists(BinaryJedisCluster.java:177)
        at org.springframework.data.redis.connection.jedis.JedisClusterKeyCommands.exists(JedisClusterKeyCommands.java:561)
        at org.springframework.data.redis.connection.RedisKeyCommands.exists(RedisKeyCommands.java:48)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
        at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.touch(RedisSessionExpirationPolicy.java:144)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:133)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.cleanupExpiredSessions(RedisIndexedSessionRepository.java:407)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:373)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:314)
        at redis.clients.jedis.Connection.authext(Connection.java:434)
        at redis.clients.jedis.Connection.connect(Connection.java:247)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:317)
        at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:2143)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:163)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:314)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:124)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:101)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:70)
        at redis.clients.jedis.BinaryJedisCluster.exists(BinaryJedisCluster.java:177)
        at org.springframework.data.redis.connection.jedis.JedisClusterKeyCommands.exists(JedisClusterKeyCommands.java:561)
        at org.springframework.data.redis.connection.RedisKeyCommands.exists(RedisKeyCommands.java:48)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
        at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.touch(RedisSessionExpirationPolicy.java:144)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:133)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.cleanupExpiredSessions(RedisIndexedSessionRepository.java:407)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.jedis.util.Pool.getResource(Pool.java:58)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:314)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:124)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:101)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:70)
        at redis.clients.jedis.BinaryJedisCluster.exists(BinaryJedisCluster.java:177)
        at org.springframework.data.redis.connection.jedis.JedisClusterKeyCommands.exists(JedisClusterKeyCommands.java:561)
        at org.springframework.data.redis.connection.RedisKeyCommands.exists(RedisKeyCommands.java:48)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.exists(DefaultedRedisConnection.java:62)
        at org.springframework.data.redis.core.RedisTemplate.lambda$hasKey$6(RedisTemplate.java:773)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228)
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188)
        at org.springframework.data.redis.core.RedisTemplate.hasKey(RedisTemplate.java:773)
        at org.springframework.session.data.redis.RedisSessionExpirationPolicy.touch(RedisSessionExpirationPolicy.java:144)
```

**Comment by marcusdacoregio** [comment]
Hi, @lijunyong. Thanks for the report.

Can you provide a minimal, reproducible sample for the issue?
