### ISSUE TITLE
Deadlock in select with left outer join out spring session

### ISSUE THREAD

**Issue by shuangyu121** [spring-projects/spring-session#2109]
**Describe the bug**
App env: websphere 9.0.5.5
database: db2 11.5

We found a large number of deadlocks in the spring session select section when there were a large number of transactions in the user environment，the error message is follow:

```
org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [SELECT S.PRIMARY_ID, S.SESSION_ID, S.CREATION_TIME, S.LAST_ACCESS_TIME, S.MAX_INACTIVE_INTERVAL, SA.ATTRIBUTE_NAME, SA.ATTRIBUTE_BYTES FROM TBL_ERKS_SPRING_SESSION S LEFT OUTER JOIN TBL_ERKS_SPRING_SESSION_ATTRIBUTES SA ON S.PRIMARY_ID = SA.SESSION_PRIMARY_ID WHERE S.SESSION_ID = ?]; DB2 SQL Error: SQLCODE=-911, SQLSTATE=40001, SQLERRMC=2, DRIVER=4.29.24; nested exception is com.ibm.db2.jcc.am.SqlTransactionRollbackException: DB2 SQL Error: SQLCODE=-911, SQLSTATE=40001, SQLERRMC=2, DRIVER=4.29.24
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:271) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.lambda$findById$1(JdbcIndexedSessionRepository.java:415) ~[spring-session-jdbc-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$$Lambda$16176/00000000597B3110.doInTransaction(Unknown Source) ~[?:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.findById(JdbcIndexedSessionRepository.java:414) ~[spring-session-jdbc-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.findById(JdbcIndexedSessionRepository.java:130) ~[spring-session-jdbc-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSession(SessionRepositoryFilter.java:351) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSessionId(SessionRepositoryFilter.java:333) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:227) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:192) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:144) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at immd.ap2.dmsadm.web.config.ExcludeSessionRepositoryFilter.doFilterInternal(ExcludeSessionRepositoryFilter.java:35) ~[classes/:?]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119) [spring-boot-2.3.5.RELEASE.jar:2.3.5.RELEASE]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) [com.ibm.ws.webcontainer.jar:?]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:197) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:979) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1119) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4238) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.handleRequest(WebAppImpl.java:2210) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1033) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.tcp.channel.impl.WorkQueueManager.requestComplete(WorkQueueManager.java:558) [?:CCX.CF [o1800.01]]
	at com.ibm.ws.tcp.channel.impl.WorkQueueManager.attemptIO(WorkQueueManager.java:608) [?:CCX.CF [o1800.01]]
	at com.ibm.ws.tcp.channel.impl.WorkQueueManager.workerRun(WorkQueueManager.java:985) [?:CCX.CF [o1800.01]]
	at com.ibm.ws.tcp.channel.impl.WorkQueueManager$Worker.run(WorkQueueManager.java:1074) [?:CCX.CF [o1800.01]]
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909) [com.ibm.ws.runtime.jar:?]
Caused by: com.ibm.db2.jcc.am.SqlTransactionRollbackException: DB2 SQL Error: SQLCODE=-911, SQLSTATE=40001, SQLERRMC=2, DRIVER=4.29.24
	at com.ibm.db2.jcc.am.b7.a(b7.java:797) ~[db2jcc4.jar:?]
	at com.ibm.db2.jcc.am.b7.a(b7.java:66) ~[db2jcc4.jar:?]
	at com.ibm.db2.jcc.am.b7.a(b7.java:140) ~[db2jcc4.jar:?]
	at com.ibm.db2.jcc.am.ResultSet.completeSqlca(ResultSet.java:4329) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.ac.h(ac.java:300) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.ac.a(ac.java:256) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.ac.c(ac.java:31) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.q.a(q.java:32) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.h.readFetch_(h.java:266) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.am.ResultSet.flowFetch(ResultSet.java:4065) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.c.f(c.java:2447) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.am.bi.a(bi.java:257) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.t4.c.a(c.java:129) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.am.ResultSet.nextX(ResultSet.java:464) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.db2.jcc.am.ResultSet.next(ResultSet.java:383) ~[db2jcc4-4.21.29.jar:?]
	at com.ibm.ws.rsadapter.jdbc.WSJdbcResultSet.next(WSJdbcResultSet.java:3124) ~[com.ibm.ws.runtime.jar:?]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$SessionResultSetExtractor.extractData(JdbcIndexedSessionRepository.java:843) ~[spring-session-jdbc-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$SessionResultSetExtractor.extractData(JdbcIndexedSessionRepository.java:838) ~[spring-session-jdbc-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617) ~[spring-jdbc-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	... 48 more
```

could you help us to solve this?

**Comment by shuangyu121** [comment]
Dear all, 
Changing the transaction level of the select left join (adding with cs after the original sql) has temporarily solved the problem. We have found out from related materials that the default transaction level used in websphere is REPEATABLE_READ, which can easily cause deadlock in a join table query. There are two ways to solve this problem, either by reducing the transaction base table of the query statement, or by splitting the join statement and replacing it with a single table with multiple queries.

**Comment by rwinch** [comment]
Thanks for the follow up @shuangyu121
