### ISSUE TITLE
A large number of sessions time out, causing a sharp increase in the connection pool.

### ISSUE THREAD

**Issue by SpireCat** [spring-projects/spring-session#2126]
**Describe the bug**
I use RedisIndexedSessionRepository to storage login sessions. There are almost 150 microservices in the cluster.
I am testing the scenario in which 100 sessions expire at the same time.
Then，every miscroservice create connections to getSession cause by onMessage() method.
This leads to overriding of my Redis server‘s max clients limit 5000.
So How can I disable RedisIndexedSessionRepository.onMessage() in some unnecessary miscroservices or do something else to avoid this problem？

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:292) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:514) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:210) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:307) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:223) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.getSession(RedisIndexedSessionRepository.java:457) ~[spring-session-data-redis-2.6.1.jar:2.6.1]
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.onMessage(RedisIndexedSessionRepository.java:543) ~[spring-session-data-redis-2.6.1.jar:2.6.1]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:263) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:253) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at org.springframework.data.redis.listener.RedisMessageListenerContainer.lambda$dispatchMessage$1(RedisMessageListenerContainer.java:1051) ~[spring-data-redis-2.6.4.jar:2.6.4]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.jedis.util.Pool.getResource(Pool.java:87) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:480) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:17) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:283) ~[spring-data-redis-2.6.4.jar:2.6.4]
        ... 16 more
Caused by: redis.clients.jedis.exceptions.JedisException: Handshake failed! SendCliAuthReq : Auth Step1 failed! Message:ERR max number of clients reached
        at redis.clients.jedis.JedisAuth.sendCliAuthReq(JedisAuth.java:118) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.JedisAuth.getCliAuthReqTokenAB(JedisAuth.java:145) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.JedisAuth.getCliAuthXxx(JedisAuth.java:94) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.JedisAuth.getPassword(JedisAuth.java:84) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:831) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2759) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:93) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]
        at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:335) ~[jedis-3.6.3-h0.gts.dsp.23.1.RC1.B009.12.r1.jar:?]

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by vpavic** [comment]
Are you aware that Spring Session (since release `2.2`) also offers [`RedisSessionRepository`](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionRepository.java)? This `SessionRepository` implementation doesn't support session events and session indexing but is in turn much more _lightweight_ in terms of its communication with Redis and will be the default Redis `SessionRepository` starting with `3.0`.

**Comment by SpireCat** [comment]
> Are you aware that Spring Session (since release `2.2`) also offers [`RedisSessionRepository`](https://github.com/spring-projects/spring-session/blob/main/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionRepository.java)? This `SessionRepository` implementation doesn't support session events and session indexing but is in turn much more _lightweight_ in terms of its communication with Redis and will be the default Redis `SessionRepository` starting with `3.0`.


Thank you for your attention.I understand what you mean, but how can I do that?I've tried use RedisSessionRepository in SessionRepositoryFilter like :
    @Bean
    @Override
    public <S extends Session> SessionRepositoryFilter<? extends Session> springSessionRepositoryFilter(
        SessionRepository<S> sessionRepository) {
        ((RedisSessionRepository) sessionRepository).setDefaultMaxInactiveInterval(Duration.ofSeconds(sessionTimeOut));
        return super.springSessionRepositoryFilter(sessionRepository);
    }

But in the end, I got this exception when I tried to restart my tomcat：
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.session.web.http.SessionRepositoryFilter]: Factory method 'springSessionRepositoryFilter' threw exception; nested exception is java.lang.ClassCastException: org.springframework.session.data.redis.RedisIndexedSessionRepository cannot be cast to org.springframework.session.data.redis.RedisSessionRepository

**Comment by vpavic** [comment]
There is a [sample project](https://github.com/spring-projects/spring-session/tree/main/spring-session-samples/spring-session-sample-boot-redis-simple) in the Spring Session codebase that shows how to set up the new `RedisSessionRepository`. More specifically, you're looking for this:
https://github.com/spring-projects/spring-session/blob/58813e9d5a1c77a4416df9033343f55b9b57db7a/spring-session-samples/spring-session-sample-boot-redis-simple/src/main/java/sample/config/SessionConfig.java#L34-L74

Note that this snippet assumes use of Spring Boot and sets things up in a way to reuse the existing configuration properties. If you're not using Spring Boot and are configuring Spring Session on your own, just remove everything related to `RedisSessionProperties`.

**Comment by SpireCat** [comment]
> There is a [sample project](https://github.com/spring-projects/spring-session/tree/main/spring-session-samples/spring-session-sample-boot-redis-simple) in the Spring Session codebase that shows how to set up the new `RedisSessionRepository`. More specifically, you're looking for this:
> 
> https://github.com/spring-projects/spring-session/blob/58813e9d5a1c77a4416df9033343f55b9b57db7a/spring-session-samples/spring-session-sample-boot-redis-simple/src/main/java/sample/config/SessionConfig.java#L34-L74
> 
> Note that this snippet assumes use of Spring Boot and sets things up in a way to reuse the existing configuration properties. If you're not using Spring Boot and are configuring Spring Session on your own, just remove everything related to `RedisSessionProperties`.

Thank you so much. So should I disable RedisHttpSessionConfiguration to avoid register RedisIndexedSessionRepository  as a sessionRepository bean?

**Comment by vpavic** [comment]
You didn't show or explain how exactly are you configuring Spring Session so my advice can only be based on assumptions.

Assuming you use Spring Boot, the linked sample application (being Spring Boot based itself) shows everything you need to do as Spring Boot's auto-configuration of Spring Session will back-off when you register your own bean of `SessionRepository` type.

If you're not using Spring Boot, you need to replace the declaration of `@EnableRedisHttpSession` with what's shown above (combination of `@EnableSpringHttpSession` and `RedisSessionRepository` bean).

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
