### ISSUE TITLE
Exception embedded connection refused

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-session#216]
~~~
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at com.xenoterracide.Application.main(Application.java:57)
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:140)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:229)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:57)
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:156)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	... 13 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:42)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:10)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:133)
	... 18 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at redis.clients.jedis.Connection.connect(Connection.java:150)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:71)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1783)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:65)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at redis.clients.util.Pool.getResource(Pool.java:40)
	... 21 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:144)
	... 28 more
~~~

here's a link to my implementation

https://github.com/xenoterracide/spring-session-redis-test-case/blob/redis/src/main/java/com/xenoterracide/Application.java

**Comment by altfatterz** [comment]
have a look https://github.com/spring-projects/spring-session/tree/master/samples/spring-embedded-redis

In your example you miss the embedded redis

**Comment by xenoterracide** [comment]
the examples in the reference documentation and the examples in spring-security angular js don't cover this, perhaps they should if no starter that'll just do this by default  is going to be provided.

**Comment by xenoterracide** [comment]
noting, that example doesn't work against the versions on the Spring IO Platform 1.1.2

**Comment by rwinch** [comment]
@xenoterracide Thank you for your feedback. 

As mentioned, you need to somehow have Redis running locally for the samples to work. Alternatively, you would need to modify the configuration to point to an external Redis instance.

Where specifically do you feel this needs to be more clear (can you provide a link)? This is described in the documentation in a number of places. For example, please refer to callout 1 in the [QuickStart - JavaConfiguration](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/httpsession.html#httpsession-spring-configuration).

**Comment by xenoterracide** [comment]
sure I get 1, but it's not a class that actually exists in Spring Session. You have to write it. Where the documentation on how to write it? the example code? why do I need a custom annotation?

The example might work if I were working with the versions the example uses, but the IO Platform obviously uses a different version since those constructors don't exist. I haven't dug into what the version difference is.

I think that a spring-boot-starter-session is really needed, and it should just have the annotation mentioned in the documentation.

**Comment by rwinch** [comment]
@xenoterracide Thanks for your feedback. I have been looking into providing embedded redis support with Spring Data Redis (see #121). However, due to all the problems we have had with supporting various Linux and Windows versions I have decided it is not worth the effort. Instead, we are going to update the samples to use an external redis instance.

**Comment by shiru4** [comment]
Thanks a lot @xenoterracide.It works now after setting up local redis server.
