### ISSUE TITLE
hazelcast session storage sporadic null pointer causes cluster outage

### ISSUE THREAD

**Issue by bitrecycling** [spring-projects/spring-session#2214]
we have a cluster of 3 nodes configured using fixed IP addresses hosted in a Spring Boot Application on external Tomcat. Hazelcast acts as Spring session storage. Every couple of days or sometimes just hours none of the node is reachable, the log is stating 
`com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!`

after looking further up in the log what might have caused this, I found a NPE, see following stacktrace.

Environment:
jdk 11.0.17
apache-tomcat 9.0.68
spring-boot 2.7.3
hazelcast 5.1.3

```
 c.h.m.i.o.MapClearExpiredOperation       : [10.172.194.22]:5701 [bycs-webportal-session-cluster-dev] [5.1.3] Missing responseHandler for com.hazelcast.map.impl.operati
on.MapClearExpiredOperation{serviceName='hz:impl:mapService', identityHash=213312459, partitionId=15, replicaIndex=0, callId=0, invocationTime=-1 (1970-01-01 00:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, tenan
tControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, expirationPercentage=10}

com.hazelcast.query.QueryException: java.lang.NullPointerException
        at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:83) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:73) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.QueryableEntry.extractAttributeValue(QueryableEntry.java:116) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.QueryableEntry.getAttributeValue(QueryableEntry.java:62) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.AbstractIndex.extractAttributeValue(AbstractIndex.java:351) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.AbstractIndex.removeEntry(AbstractIndex.java:145) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.Indexes.removeEntry(Indexes.java:394) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.Indexes.removeEntry(Indexes.java:382) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.removeIndex(IndexingMutationObserver.java:184) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onEvictRecord(IndexingMutationObserver.java:78) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onEvictRecord(CompositeMutationObserver.java:143) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.DefaultRecordStore.evict(DefaultRecordStore.java:531) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntryAndPublishExpiryEvent(AbstractEvictableRecordStore.java:128) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.expiry.ExpirySystemImpl.evictExpiredKeys(ExpirySystemImpl.java:394) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.expiry.ExpirySystemImpl.evictExpiredEntries(ExpirySystemImpl.java:315) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.recordstore.AbstractEvictableRecordStore.evictExpiredEntries(AbstractEvictableRecordStore.java:78) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.map.impl.operation.MapClearExpiredOperation.run(MapClearExpiredOperation.java:68) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1.3.jar:5.1.3]
Caused by: java.lang.NullPointerException: null
 at org.springframework.session.MapSession.getAttribute(MapSession.java:173) ~[spring-session-core-2.7.0.jar:2.7.0]
        at org.springframework.session.hazelcast.Hazelcast4PrincipalNameExtractor.extract(Hazelcast4PrincipalNameExtractor.java:37) ~[spring-session-hazelcast-2.7.0.jar:2.7.0]
        at org.springframework.session.hazelcast.Hazelcast4PrincipalNameExtractor.extract(Hazelcast4PrincipalNameExtractor.java:32) ~[spring-session-hazelcast-2.7.0.jar:2.7.0]
        at com.hazelcast.query.impl.getters.ExtractorGetter.getValue(ExtractorGetter.java:49) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.getters.Getter.getValue(Getter.java:40) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.getters.Getter.getValue(Getter.java:48) ~[hazelcast-5.1.3.jar:5.1.3]
        at com.hazelcast.query.impl.getters.Extractors.extract(Extractors.java:81) ~[hazelcast-5.1.3.jar:5.1.3]
        ... 24 common frames omitted

```

**Comment by bitrecycling** [comment]
This might be a subsequent error... I am closing this and open another issue if this happens again or I can provide more information
