### ISSUE TITLE
HttpSession.invalidate() 

### ISSUE THREAD

**Issue by whatColorSSS** [spring-projects/spring-session#2339]
**Describe the bug**
Failure to clear cache information in Redis in a timely manner when i execute _HttpSession.invalidate()_  in HandlerInterceptor 

**To Reproduce**
Spring boot Project named **S_A** and  Spring boot Project named **S_B** use the same redis
S_A  use spring-session-data-redis-2.3.3.RELEASE.jar
S_B  use  spring-session-data-redis-2.6.3.jar

1. S_A execute _HttpSession.setAttribute("entity",S_A.xxxDTO);_
2. S_A execute _request.getSession(true).invalidate();_  
And then , S_B will throw JdkSerializationRedisSerializer.deserialize exception because ClassNotFound

After debugging, I found that _HttpSession.invalidate()_ will get session from redis befor delete key from redis. 

This behavior occurs in both services S_A and S_B, Therefore, when S_B get session from Redis, it must be an error because S_B did not introduce _S_A.xxxDTO_

**Expected behavior**
1. I don't understand why S_B will execute _RedisIndexedSessionRepository.getSession(String id, boolean allowExpired)_ when I  execute  _HttpSession.invalidate()_  in S_A ?   (_Maybe it's some kind of listener?_)
2. Why  the result Of S_B getSession is not null after S_A delete redis key 

```
	private RedisSession getSession(String id, boolean allowExpired) {
		Map<Object, Object> entries = getSessionBoundHashOperations(id).entries();
		if (entries.isEmpty()) {
			return null;
		}
		MapSession loaded = loadSession(id, entries);
		if (!allowExpired && loaded.isExpired()) {
			return null;
		}
		RedisSession result = new RedisSession(loaded, false);
		result.originalLastAccessTime = loaded.getLastAccessedTime();
		return result;
	}

	private BoundHashOperations<Object, Object, Object> getSessionBoundHashOperations(String sessionId) {
		String key = getSessionKey(sessionId);
		return this.sessionRedisOperations.boundHashOps(key);
	}
````

Exception
```
2023-06-27 11:57:00.167 [TID: N/A] [springSessionRedisMessageListenerContainer-5701] WARN  RedisMessageListenerContainer.invokeErrorHandler():305 - Execution of message listener failed, and no ErrorHandler has been set. org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: com.moan.hoe.common.dto.UserAuthorityDto
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:84) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:380) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:324) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:309) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:223) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.getSession(RedisIndexedSessionRepository.java:457) ~[spring-session-data-redis-2.6.3.jar:2.6.3]
	at org.springframework.session.data.redis.RedisIndexedSessionRepository.onMessage(RedisIndexedSessionRepository.java:543) ~[spring-session-data-redis-2.6.3.jar:2.6.3]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.executeListener(RedisMessageListenerContainer.java:263) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.processMessage(RedisMessageListenerContainer.java:253) ~[spring-data-redis-2.6.9.jar:2.6.9]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lambda$dispatchMessage$1(RedisMessageListenerContainer.java:1051)
```

**Comment by marcusdacoregio** [comment]
Hi @whatColorSSS.

The behavior is explained in the `RedisSessionIndexedRepository` [javadoc](https://github.com/spring-projects/spring-session/blob/dbd9567e2342624eb1f2ee696e50c926c1e486bc/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L177C3-L181).

Should you have more questions related to this, feel free to ask.
