### ISSUE TITLE
DuplicateKeyException for spring_session_attributes_pk in spring-session-jdbc

### ISSUE THREAD

**Issue by jankoh** [spring-projects/spring-session#2564]
**Describe the bug**
We have a project in which we use Spring Boot's SAML authentication together with spring-session-jdbc and a PostgreSQL database. Quite regularly we get a 500 backend error with the following debug output:

```log
2023-10-25T13:37:26.541+02:00 DEBUG 2775123 --- [nio-8080-exec-1] o.s.security.web.FilterChainProxy        : Securing GET /api/users/me
2023-10-25T13:37:26.547+02:00 DEBUG 2775123 --- [nio-8080-exec-1] .s.s.w.s.ForceEagerSessionCreationFilter : Created session eagerly
2023-10-25T13:37:26.561+02:00 DEBUG 2775123 --- [nio-8080-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-10-25T13:37:26.622+02:00 DEBUG 2775123 --- [nio-8080-exec-2] o.s.security.web.FilterChainProxy        : Securing GET /api/users/me
2023-10-25T13:37:26.628+02:00 DEBUG 2775123 --- [nio-8080-exec-3] o.s.security.web.FilterChainProxy        : Securing GET /sso/saml/login
2023-10-25T13:37:26.628+02:00 DEBUG 2775123 --- [nio-8080-exec-4] o.s.security.web.FilterChainProxy        : Securing GET /sso/saml/login
2023-10-25T13:37:26.629+02:00 DEBUG 2775123 --- [nio-8080-exec-2] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2023-10-25T13:37:26.654+02:00 DEBUG 2775123 --- [nio-8080-exec-5] o.s.security.web.FilterChainProxy        : Securing GET /sso/saml/login
2023-10-25T13:37:26.654+02:00 DEBUG 2775123 --- [nio-8080-exec-6] o.s.security.web.FilterChainProxy        : Securing GET /sso/saml/login
2023-10-25T13:37:26.679+02:00 ERROR 2775123 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO SPRING_SESSION_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)
VALUES (?, ?, ?)
]; ERROR: duplicate key value violates unique constraint "spring_session_attributes_pk"
  Detail: Key (session_primary_id, attribute_name)=(713e15fd-0057-4081-88d3-57826f469823, org.springframework.security.saml2.provider.service.web.HttpSessionSaml2AuthenticationRequestRepository.SAML2_AUTHN_REQUEST) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:254) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1572) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.insertSessionAttributes(JdbcIndexedSessionRepository.java:561) ~[spring-session-jdbc-3.1.3.jar:3.1.3]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.lambda$save$11(JdbcIndexedSessionRepository.java:912) ~[spring-session-jdbc-3.1.3.jar:3.1.3]
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68) ~[spring-tx-6.0.13.jar:6.0.13]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-6.0.13.jar:6.0.13]
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67) ~[spring-tx-6.0.13.jar:6.0.13]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.save(JdbcIndexedSessionRepository.java:894) ~[spring-session-jdbc-3.1.3.jar:3.1.3]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:473) ~[spring-session-jdbc-3.1.3.jar:3.1.3]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:139) ~[spring-session-jdbc-3.1.3.jar:3.1.3]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:228) ~[spring-session-core-3.1.3.jar:3.1.3]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:146) ~[spring-session-core-3.1.3.jar:3.1.3]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-3.1.3.jar:3.1.3]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.13.jar:6.0.13]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.13.jar:6.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.0.13.jar:6.0.13]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.13.jar:6.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.13.jar:6.0.13]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.13.jar:6.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "spring_session_attributes_pk"
  Detail: Key (session_primary_id, attribute_name)=(713e15fd-0057-4081-88d3-57826f469823, org.springframework.security.saml2.provider.service.web.HttpSessionSaml2AuthenticationRequestRepository.SAML2_AUTHN_REQUEST) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.6.0.jar:42.6.0]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152) ~[postgresql-42.6.0.jar:42.6.0]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) ~[spring-jdbc-6.0.13.jar:6.0.13]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:648) ~[spring-jdbc-6.0.13.jar:6.0.13]
	... 41 common frames omitted
```

Pressing F5 in the browser to releoad the page leads to being (correctly) redirected to the SAML-Login-Page.

I figured, I can reproduce this with a clean (empty) `spring_session_attributes` table, a freshly started backend, and a new browser incognito window loading the frontend page. If I clear the session-cookie within the browser window, I can trigger the dupplicate key, again.

Intrestingly, though JDBC's update-Method is called, an insert is to be performed. I implemented a (IMHO quite terrible) workaround by using an insert-trigger on the database preventing the insert when an identical key is already present. 

We also have another applications having identical configuration without isses, as far as we know.

**To Reproduce**
- clean database
- freshly started backend application
- new incognito browser  window (no cookies set)

**Expected behavior**
Session should be stored in the databases

**Comment by marcusdacoregio** [comment]
Hi, @jankoh. Can you provide a minimal, reproducible sample that demonstrates the issue? Note that you can [expose the `PostgreSqlJdbcIndexedSessionRepositoryCustomizer` as a bean](https://github.com/spring-projects/spring-session/blob/main/spring-session-jdbc/src/main/java/org/springframework/session/jdbc/PostgreSqlJdbcIndexedSessionRepositoryCustomizer.java) and that would customize the `createSessionAttributeQuery` to update if there is a conflict on the insert.

**Comment by jankoh** [comment]
@marcusdacoregio providing a minimal example might take w while. As written, we have two projects having identical configuration (at least to our knowlege) one showing this bug, one working fine. I'm not completely sure what might cause this; probably some parallel requests from frontend confuse the session creation (in the debug output there's three requests to the saml login when simply opening the page one time in the browser). 

For the moment, using the trigger preventing a second insert works; but I'll try the customizer, which seems a cleaner solution. 

Anyways, I'll get back to this case as soon possible to try providing an example.

**Comment by romainlouvet** [comment]
same problem for me @jankoh, Quite regularly we get a 500 with this error ... :/ 

did you manage to get around the problem ?

thanks

**Comment by romainlouvet** [comment]
@marcusdacoregio like this ?

```
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.session.config.SessionRepositoryCustomizer;
import org.springframework.session.jdbc.JdbcIndexedSessionRepository;
import org.springframework.session.jdbc.config.annotation.web.http.EnableJdbcHttpSession;
import org.springframework.session.jdbc.config.annotation.web.http.JdbcHttpSessionConfiguration;

@Configuration
@EnableJdbcHttpSession
public class HttpSessionConfig extends JdbcHttpSessionConfiguration {

  @Bean
  public PostgreSqlJdbcHttpSessionCustomizer jdbcHttpSessionCustomizer() {
    return new PostgreSqlJdbcHttpSessionCustomizer();
  }

  public class PostgreSqlJdbcHttpSessionCustomizer
      implements SessionRepositoryCustomizer<JdbcIndexedSessionRepository> {

    private static final String CREATE_SESSION_ATTRIBUTE_QUERY = """
        INSERT INTO %TABLE_NAME%_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)
        VALUES (?, ?, ?)
        ON CONFLICT (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
        DO UPDATE SET ATTRIBUTE_BYTES = EXCLUDED.ATTRIBUTE_BYTES
        """;

    @Override
    public void customize(JdbcIndexedSessionRepository sessionRepository) {
      sessionRepository.setCreateSessionAttributeQuery(CREATE_SESSION_ATTRIBUTE_QUERY);
    }

  }
}
```

**Comment by marcusdacoregio** [comment]
Yes, the query itself would depend on the RDBMS and your business needs, see https://docs.spring.io/spring-session/reference/3.2-SNAPSHOT/configuration/jdbc.html#customize-sql-queries

**Comment by mindhaq** [comment]
As a reminder:

In one spring backend app (3.4.x) with a custom SQL as described in the docs, I had this exception today a couple of times, for a session ID which was then seemingly removed from the database.

I have no idea how to reproduce that.
