### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by rolandgroen** [spring-projects/spring-session#483]
After about 3 or 4 days of usage (300 concurrent users) our application stopped responding, and the log shows an "java.lang.OutOfMemoryError: unable to create new native thread" error. The default implementation of the RedisMessageListenerContainer uses a SimpleAsyncTaskExecutor that creates a thread on every call to dispatchMessage. This somehow repletes the available threads. The JDK version is 1.7.0_79-b15, 64-Bit.

See also: https://plumbr.eu/outofmemoryerror/unable-to-create-new-native-thread

The solution is quite simple, make use of one of the java.util.concurrent.Executors to dispatch the message.

The stack is:

2016-04-01 08:46:47,507 [redisMessageListenerContainer-1] ERROR org.springframework.data.redis.listener.RedisMessageListenerContainer - SubscriptionTask aborted with exception:
java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:714)
at org.springframework.core.task.SimpleAsyncTaskExecutor.doExecute(SimpleAsyncTaskExecutor.java:192)
at org.springframework.core.task.SimpleAsyncTaskExecutor.execute(SimpleAsyncTaskExecutor.java:166)
at org.springframework.core.task.SimpleAsyncTaskExecutor.execute(SimpleAsyncTaskExecutor.java:147)
at org.springframework.data.redis.listener.RedisMessageListenerContainer.dispatchMessage(RedisMessageListenerContainer.java:948)
at org.springframework.data.redis.listener.RedisMessageListenerContainer.access$1400(RedisMessageListenerContainer.java:61)
at org.springframework.data.redis.listener.RedisMessageListenerContainer$DispatchMessageListener.onMessage(RedisMessageListenerContainer.java:939)
at org.springframework.data.redis.connection.jedis.JedisMessageListener.onPMessage(JedisMessageListener.java:43)
at redis.clients.jedis.BinaryJedisPubSub.process(BinaryJedisPubSub.java:102)
at redis.clients.jedis.BinaryJedisPubSub.proceedWithPatterns(BinaryJedisPubSub.java:69)
at redis.clients.jedis.BinaryJedis.psubscribe(BinaryJedis.java:3152)
at org.springframework.data.redis.connection.jedis.JedisConnection.pSubscribe(JedisConnection.java:2681)
at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.eventuallyPerformSubscription(RedisMessageListenerContainer.java:763)
at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:730)
at java.lang.Thread.run(Thread.java:745)

**Comment by tsachev** [comment]
@rolandgroen I run into the same issue some time ago. Unfortunately spring-data-redis will create a new thread by default for *every* event received from redis, even in cases they are not interesting for spring sesssion :(.
See #314 for explanation and http://docs.spring.io/spring-session/docs/current/reference/html5/#redis-taskexecutor for how to fix this in recent versions.
Keep in mind that in my case the actual problem was caused by different thing, but it just cloudn't show up, because redis message listener tried to create a lot of short lived threads, and it if failed when there are no more resources. So when you configure custom thread executor(s) expect to see the the same problem again, but hopefully with more accurate indication where the problem is.

**Comment by rolandgroen** [comment]
@tsachev, thank you for your response. I did find a way to inject the taskExecutor by defining a bean called springSessionRedisSubscriptionExecutor. In version 1.1.1 I had to do it by overriding the  RedisHttpSessionConfiguration.redisMessageListenerContainer method. 

I see you are right about the fact that the issue is actually in the spring-data-redis.

**Comment by rwinch** [comment]
@tsachev @rolandgroen Thanks for the feedback. I'm strongly reconsidering providing a better default for Spring Session's thread pool. I'm wondering if we should max the pool at 200 to align with Tomcat's pool. Thoughts?

**Comment by rolandgroen** [comment]
We've set the pool size to 10 (Executors.newFixedThreadPool(10)) and we haven't seen any trouble anymore. I was actually thinking of moving to Executors.newSingleThreadExecutor(). The pool size should match the (reasonable) amount of concurrent connections to the redis backend. Remember, the pool has a queue also.

**Comment by rwinch** [comment]
@rolandgroen Can you create a new ticket for us to track setting the default pool size? As @tsachev pointed out there was a ticket (I believe he created it), but I closed that as won't fix. Given the Redis team will not fix it on their end and I have seen a lot of problems without a default size, I think we need to revisit this.

**Comment by rolandgroen** [comment]
@rwinch at your service.

**Comment by rolandgroen** [comment]
Just raised: https://jira.spring.io/browse/DATAREDIS-499

**Comment by tsachev** [comment]
@rolandgroen I did not mean that the problem is spring-data, has unreasonable default that they do not want to change. But tried to warn you that changing from `SimpleAsyncTaskExecutor` (which creates new thread for every event), to thread pool executor might not be enough to solve your problem. It may be just the first thing that shows up after your jvm is out of resources, but you might have another leak also that will manifest after the fix.
