### ISSUE TITLE
java.lang.IllegalStateException: Unable to configure LocalContainerEntityManagerFactoryBean from @EntityScan, ensure an appropriate bean is registered.

### ISSUE THREAD

**Issue by jltnf54** [spring-projects/spring-session#545]
Trying to use httpsession-jdbc-boot with websockets.  application does not startup extending

AbstractSessionWebSocketMessageBrokerConfigurer

```
java.lang.IllegalStateException: Unable to configure LocalContainerEntityManagerFactoryBean from @EntityScan, ensure an appropriate bean is registered.
    at org.springframework.util.Assert.state(Assert.java:392)
    at org.springframework.boot.orm.jpa.EntityScanRegistrar$EntityScanBeanPostProcessor.afterSingletonsInstantiated(EntityScanRegistrar.java:148)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:792)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
    at com.expd.systems.company.Application.main(Application.java:19)
```

**Comment by rwinch** [comment]
Can you clarify how you are reproducing the issue? Are you simply using the [websocket](https://github.com/spring-projects/spring-session/tree/master/samples/websocket) sample but with JDBC? If not, please provide details of how to reproduce

**Comment by jltnf54** [comment]
yes using spring websocket example with jdbc and jpa.  I can provide an example if needed

**Comment by vpavic** [comment]
Closing due to lack of feedback. Please re-open the issue if you can provided more details.
