### ISSUE TITLE
Spring session unable to connect to Redis sentinel

### ISSUE THREAD

**Issue by adithshenoy** [spring-projects/spring-session#554]
Hi @rwinch,

I'm using spring session 1.1.1.RELEASE to manage my applications session.

A redis cluster is set up on separate nodes. For the application to correctly connect to the node serving as the master, application node includes twemproxy. This means that the redis related communication goes through localhost and gets routed to the redis master node via this proxy.

Confirmation of access to redis master:
Master and twemproxy are up and listening on the correct port
We are able to establish connection
redis-cli -h localhost ping
PONG
There are no firewall issues

In my application. i am giving localhost and 6379 to connect but is not working.

```
spring.redis.host: localhost
spring.redis.port: 6379 
```

getting the below error:

```
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.3.3.RELEASE)

Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/session/data/redis/config/annotation/web/http/RedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unexpected end of stream.; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
    at com.rakuten.point.pointclub.PointClubApplication.main(PointClubApplication.java:20)
    ... 6 more
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unexpected end of stream.; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
    at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:47)
    at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:36)
    at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
    at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
    at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:210)
    at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:571)
    at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:69)
    at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.configure(ConfigureNotifyKeyspaceEventsAction.java:50)
    at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:176)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
    ... 22 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
    at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
    at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
    at redis.clients.jedis.Protocol.process(Protocol.java:141)
    at redis.clients.jedis.Protocol.read(Protocol.java:205)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
    at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
    at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
    at redis.clients.jedis.Jedis.configGet(Jedis.java:2541)
    at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:569)
    ... 27 more
```

**Comment by AdithShenoy** [comment]
Hi @CNapo,

I guess the link you mentioned is about spring having auto configuration to redis cluster which might require 1.4. However, we have a proxy in between. This setup should work with 1.3 I feel.

**Comment by rwinch** [comment]
@AdithShenoy Did you try with the latest versions?

**Comment by AdithShenoy** [comment]
@rwinch - Latest version of spring? You mean 1.4?

**Comment by chensy0203** [comment]
Latest release version of spring-session is 1.2.1.
It also has the same problem.
Is there any other solution ? such as config to not to create bean with name 'enableRedisKeyspaceNotificationsInitializer'?

**Comment by AdithShenoy** [comment]
Hi @rwinch 

I have moved to latest reelases of 1.4 spring boot and spring 1.2.1.

Am still facing the issue of 
"org.springframework.data.redis.RedisConnectionFailureException","message":"Unexpected end of stream.; nested exception is redis.clients.jedis.exceptions.JedisConnectionException"

in a Redis Sentinel setup having 3 redis instances. 

Is Spring session tested with a redis sentinel setup? Is there a sample redis sentinel application deployed anywhere that i can have a look at?

**Comment by roaporl** [comment]
I have the same problems. How are the things going ? 

I use spring-session:1.3.0.RELEASE  and spring-session-data-redis:1.3.0.RELEASE .

**Comment by edethoor** [comment]
To work with redis, you're application use Spring data Redis.
Spring Data redis support redis sentinel cluster by connecting directly to the different sentinel nodes : http://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:sentinel
=> spring.redis.sentinel.nodes

I've had the same error than you when in my setup i have try to use an haproxy on top of sentinel nodes and have a service IP configured in my application to connect to redis. Spring Data Redis need to communicate directly to the sentinel nodes.

**Comment by wufaman** [comment]
@roaporl 这个问题你解决了么？

**Comment by hotdust** [comment]
1.3.3 release still have same problem

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
