### ISSUE TITLE
Mismatched constant names for the HTTP session id in a websocket context

### ISSUE THREAD

**Issue by smithsos** [spring-projects/spring-session#561]
Both SessionRepositoryMessageInterceptor from SpringSession and HttpSessionHandshakeInterceptor define constants for the HTTP session id.

Spring session defines the constant as *SPRING.SESSION.ID* and spring-websockets defines it as *HTTP.SESSION.ID*.

The constants are different and this leads to an null pointer exception when HttpSessionHandshakeInterceptor is enabled. The stacktrace is below.

````
[ERROR] 2016-06-27 11:52:59.679 [http-nio-8080-exec-8] WebSocketConnectHandlerDecoratorFactory:87 - Error publishing org.springframework.session.web.socket.events.SessionConnectEvent[source=SessionWebSocketHandler [delegate=SubProtocolWebSocketHandler[StompSubProtocolHandler[v10.stomp, v11.stomp, v12.stomp]]]].
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_91]
	at org.springframework.session.web.socket.handler.WebSocketRegistryListener.registerWsSession(WebSocketRegistryListener.java:118) ~[spring-session-1.2.0.RELEASE.jar:?]
	at org.springframework.session.web.socket.handler.WebSocketRegistryListener.afterConnectionEstablished(WebSocketRegistryListener.java:86) ~[spring-session-1.2.0.RELEASE.jar:?]
	at org.springframework.session.web.socket.handler.WebSocketRegistryListener.onApplicationEvent(WebSocketRegistryListener.java:67) ~[spring-session-1.2.0.RELEASE.jar:?]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166) ~[spring-context-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138) ~[spring-context-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382) ~[spring-context-4.3.0.RELEASE.jar:4.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336) ~[spring-context-4.3.0.RELEASE.jar:4.3.0.RELEASE]
```

The session id is present in the attributes map under the key HTTP.SESSION.ID. Spring session version 1.2.0.RELEASE. Spring websocket version is 4.3.0.RELEASE.

**Comment by wgorder** [comment]
@smithsos  did you figure out a work around.  I think I might be seeing the same thing. @rwinch is this a known issue or are we doing something wrong?  I have things set up as outlined in the docs.  I am running spring boot 1.3.x.

**Comment by smithsos** [comment]
We worked around this with a bit of a hack. We created a session copying interceptor that copies the one constant to the other, the relevant interceptor code is below. We are pretty keen to remove this and get a proper solution though.

```
    @Override
    public boolean beforeHandshake(ServerHttpRequest request, ServerHttpResponse response, WebSocketHandler wsHandler, Map<String, Object> attributes) throws Exception {
        if (attributes.containsKey(HTTP_SESSION_ID_ATTR_NAME)) {
            attributes.put(SPRING_SESSION_ID_ATTR_NAME, attributes.get(HTTP_SESSION_ID_ATTR_NAME));
        }
        return true;
    }
```

**Comment by wgorder** [comment]
@smithsos  thanks for the reply.

**Comment by IsmaTeddy** [comment]
Any solution for this problem?
