### ISSUE TITLE
about use twemproxy, initialization error

### ISSUE THREAD

**Issue by kkrgwbj** [spring-projects/spring-session#572]
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Unexpected end of stream.; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:212)
	at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:573)
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.getNotifyOptions(ConfigureNotifyKeyspaceEventsAction.java:74)
	at org.springframework.session.data.redis.config.ConfigureNotifyKeyspaceEventsAction.configure(ConfigureNotifyKeyspaceEventsAction.java:55)
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet(RedisHttpSessionConfiguration.java:224)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 38 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:226)
	at redis.clients.jedis.Jedis.configGet(Jedis.java:2578)
	at org.springframework.data.redis.connection.jedis.JedisConnection.getConfig(JedisConnection.java:571)
	... 43 more

**Comment by liuanxin** [comment]
Just like you

**Comment by smartwjw** [comment]
encounter the same problem.

**Comment by roaporl** [comment]
me too

**Comment by bigbigwood** [comment]
same problem. anyone has solution?

**Comment by rwinch** [comment]
@christophstrobl Any ideas on this one?

**Comment by bigbigwood** [comment]
@rwinch thanks for the response.. 

Currently we're trying to use spring-session and redis by using twemproxy to manage the redis cluster, but we found that twemproxy is not able to support 'PUBLISH' and 'PSUBSCRIBE' commands, and spring-session-redis solution is sending/listening events to redis... 

My question is: if there is a way to disable those events in spring-session-redis solution?
