### ISSUE TITLE
Upgrade to Spring Boot 1.4.1.RELEASE and Spring Data GemFire 1.8.4.RELEASE

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-session#632]
When _Spring Session's_, _Spring Boot_ dependency is upgraded to **1.4.0.RELEASE**, and _Spring Data GemFire_ is upgraded to **1.8.2.RELEASE**, the `:samples:httpsession-gemfire-boot` sample fails due to an Exception in GemFire indicating `NoSubscriptionServersAvailableException`.  Essentially, the GemFire cache client application cannot locate and connect to the forked GemFire Server process.

It turns out, the logic coordinating the client with the server startup and interaction is no longer correct based on recent changes to _Spring Data GemFire_ in **1.8**.

**Comment by jxblum** [comment]
Hi @rwinch -

I am following up because I have not seen any activity on this PR and I am wondering whether you are planning a 1.3 M3 release?

This PR includes a couple important changes:

First, the PR upgrades _Spring Session's_ dependency on _Spring Framework_ to `4.3.2.RELEASE` (from `4.2.5`)  and _Spring Boot_ to `1.4.0.RELEASE` (from `3.x`).  However, since this PR was submitted, both SF and SB have moved to `4.3.3.RELEASE` and `1.4.1.RELEASE`, respectively.  Additionally, even SDG `1.8.4.RELEASE` is now available.

Rebasing _Spring Session_ on the latest SF and SB releases seems to be a key theme in 1.3, right?

Second, I made several critical modifications to the _Spring Session Data GemFire_ module based on updates in SDG `1.8.2.RELEASE` that would be beneficial to _Spring Session_ users using Pivotal GemFire/Apache Geode.

I did not merge this PR to `master` initially to give you a chance to review the changes and address the issue with the failing (Redis Json sample?) integration test based on the _Spring Boot_ upgrade.

I am currently looking into updating this PR now, again, with the latest versions of SF, SB and the SD modules.  Stay tuned...

Thanks,
John

**Comment by jxblum** [comment]
Update...

Running the _Spring Session_ build (`$ gradlew clean build install`) leads to the following test failure...

* `HttpRedisJsonTest`, caused by...

```
samples.HttpRedisJsonTest > Successful Login test FAILED
    geb.error.UnexpectedPageException: At checker page verification failed for page samples.pages.HomePage
        at geb.navigator.NonEmptyNavigator.click(NonEmptyNavigator.groovy:492)
        ...

        Caused by:
        Assertion failed: 

        driver.title == "Spring Session Sample - Home"
        |      |     |
        |      null  false
        org.openqa.selenium.htmlunit.HtmlUnitDriver@21f65af7
            at samples.pages.HomePage._clinit__closure1(HomePage.groovy:13)
            ... 15 more
```

Which is indirectly caused by:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.util.Collections$UnmodifiableSet: no default no-arguments constructor found
     at [Source: N/A; line: -1, column: -1]
    	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261) ~[jackson-databind-2.8.3.jar:2.8.3]
    	... 89 common frames omitted
```

Which is no doubt caused by the version of *Jackson* that _Spring Boot_ `1.4.1.RELEASE` is pulling in vs. _Spring Boot_ `1.3.x`.

Additionally, several failures occurred in the `spring3Test` test suite, Redis tests, if I tried to upgrade the SD Redis module to latest maintenance version, `1.7.4.RELEASE` (from `1.7.1.RELEASE`), which is undoubtedly caused by the incompatible _Spring_ version (`3.x`) relative to the SF version SD Redis `1.7.4.RELEASE` expects...

```
Caused by: java.lang.NoSuchMethodError: org.springframework.core.serializer.support.DeserializingConverter.<init>(Ljava/lang/ClassLoader;)V
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.<init>(JdkSerializationRedisSerializer.java:53)
	at org.springframework.data.redis.core.RedisTemplate.afterPropertiesSet(RedisTemplate.java:119)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	... 88 more
```

This [constructor](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/core/serializer/support/DeserializingConverter.html#DeserializingConverter-java.lang.ClassLoader-) did not exist prior to SF `4.2.1`, and it is apparent that SD Redis `1.7.4.RELEASE` (vs. `1.7.1.RELEASE`) is now making use of this (relatively) new, overloaded constructor, which complicates things for the _Spring Session_, `spring3Test` test suite.

I have successfully upgraded SD GemFire and SD MongoDB to their latest releases, `1.8.4` & `1.9.4`, respectively.  With the latest versions of SF and SB, I am able to run the _Spring Session_ build with...

```
$ gradlew clean build install -x :samples:httpsession-redis-json:integrationTest
```

Thanks,
John
