### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException with Spring Session Data Redis 2.0

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-session#854]
Hi

I tried to build Spring Session Data Redis 2.0 application using Maven 3.5.0. However build failed with exception:

java.lang.ArrayIndexOutOfBoundsException: 25524
	at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseEpilog(MXParser.java:1604)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1434)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)

If I remove spring-session-data-redis dependency from pom.xml then build succeeds.
I attached sample application to reproduce this issue. Please share advice or workaround.
[rest-samples.zip](https://github.com/spring-projects/spring-session/files/1228526/rest-samples.zip)

**Comment by sergey-morenets** [comment]
Fixed after removing all Spring-related entries in local Maven repository.
