### ISSUE TITLE
When session object structure changes the whole thing completely broken

### ISSUE THREAD

**Issue by ipeisong** [spring-projects/spring-session#90]
I have SecurityObject in session, and when I add new constructor, here is the errors:
```
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: io.vord.webapp.domain.SecurityDetails; local class incompatible: stream classdesc serialVersionUID = -4384170468320524886, local class serialVersionUID = 0
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:64)
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:34)
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:39)
	... 63 common frames omitted
```

And it only throws 500 error, however, this behaviour is not reasonable. If an object version is outdated, shouldn't it be considered session expired and return null? Now the application is broken on this condition, the only thing I can do is to flush all database. Any better way to handle this?

**Comment by rwinch** [comment]
I think the behavior is correct. If the object in session is non-passive, we should fail fast. This is no different than how Hibernate would behave if you used Java Serialization to persist an object to a database that changed.

In most cases, I would want to use a custom serialization to ensure that objects are read and written in a passive way. You can customize the way the objects are [serialized](http://docs.spring.io/spring-data/redis/docs/1.4.0.RELEASE/reference/html/#redis:serializer) into the database. You can customize how the values are persisted using something like the following:

```java
    @Primary
    @Bean
    public RedisTemplate<String,ExpiringSession> sessionRedisTemplate(RedisConnectionFactory connectionFactory) {
        RedisTemplate<String, ExpiringSession> template = new RedisTemplate<String, ExpiringSession>();
        template.setKeySerializer(new StringRedisSerializer());
        template.setHashKeySerializer(new StringRedisSerializer());

        // customize the hash value serializer (default is JdkSerializationRedisSerializer)
        template.setHashValueSerializer(...);

        template.setConnectionFactory(connectionFactory);
        return template;
    }
```
