### ISSUE TITLE
SpelEvaluationException: EL1008E: Property or field 'authentication' cannot be found on object of type 'java.util.LinkedHashMap' - maybe not public?

### ISSUE THREAD

**Issue by alterhu2020** [spring-projects/spring-session#933]
#
These are libraries i used here in springboot project.
1. `spring-boot-starter-security`: 2.0.0.M6
2. `spring-session-data-redis`: 2.0.0.RC1
3. `spring-boot-starter-data-redis`: 2.0.1.RELEASE

```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
```
And the spring security config code as below
```
@EnableWebSecurity(debug = true)
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {
        UserDetails userDetails = User.withDefaultPasswordEncoder()
                .username("test").password("test").roles("USER").build();
        auth.inMemoryAuthentication().withUser(userDetails);
    }
//..........................
}
```
And the spring session config code as below
```
@EnableRedisHttpSession
public class CustomSessionRedisConfiguration {

    /**
     * @return
     */
    @Bean(name = {"springSessionDefaultRedisSerializer"})
    RedisSerializer<Object> defaultRedisSerializer() {
        GenericJackson2JsonRedisSerializer result = new 
       GenericJackson2JsonRedisSerializer(new ObjectMapper());
        return result;
    }
}
```
I had read the official example code to make the redis sesion stored into json format, as showed in this config file[https://github.com/spring-projects/spring-session/blob/master/samples/boot/redis-json/src/main/java/sample/config/SessionConfig.java](https://github.com/spring-projects/spring-session/blob/master/samples/boot/redis-json/src/main/java/sample/config/SessionConfig.java), but it still have no luck. All they show the below error message when I open the main url http://127.0.0.1:9999/api/
```
org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'authentication' cannot be found on object of type 'java.util.LinkedHashMap' - maybe not public?
	org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213)
	org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:100)
	org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:87)
	org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:52)
	org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:115)
	org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:240)
	org.springframework.session.data.redis.RedisOperationsSessionRepository$PrincipalNameResolver.resolvePrincipal(RedisOperationsSessionRepository.java:859)
	org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.<init>(RedisOperationsSessionRepository.java:707)
	org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:448)
	org.springframework.session.data.redis.RedisOperationsSessionRepository.findById(RedisOperationsSessionRepository.java:409)
	org.springframework.session.data.redis.RedisOperationsSessionRepository.findById(RedisOperationsSessionRepository.java:245)
	org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.lambda$getRequestedSessionId$0(SessionRepositoryFilter.java:359)
	java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getRequestedSessionId(SessionRepositoryFilter.java:360)
	org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:303)
	org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:196)
	javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
	org.springframework.security.web.debug.DebugRequestWrapper.getSession(DebugFilter.java:175)
	javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231)
	org.springframework.security.web.context.HttpSessionSecurityContextRepository.loadContext(HttpSessionSecurityContextRepository.java:110)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:100)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	org.springframework.security.web.debug.DebugFilter.invokeWithWrappedRequest(DebugFilter.java:90)
	org.springframework.security.web.debug.DebugFilter.doFilter(DebugFilter.java:77)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:146)
	org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
```
Guys, do you have any guide how to use the redis jackson in spring-session? thanks

**Comment by Ramblurr** [comment]
I also ran into this error when reloading the principal on every request with a filter.

I'm using spring-session with JDBC, and it was working with no problem until I added this filter (see below).

### Exception

```

org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'authentication' cannot be found on object of type 'org.springframework.security.authentication.UsernamePasswordAuthenticationToken' - maybe not public?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:226)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:81)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:51)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:233)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$PrincipalNameResolver.resolvePrincipal(JdbcOperationsSessionRepository.java:759)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$JdbcSession.getPrincipalName(JdbcOperationsSessionRepository.java:684)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$2$1.setValues(JdbcOperationsSessionRepository.java:429)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:875)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository$2.doInTransactionWithoutResult(JdbcOperationsSessionRepository.java:421)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:417)
	at org.springframework.session.jdbc.JdbcOperationsSessionRepository.save(JdbcOperationsSessionRepository.java:129)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:245)
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:217)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:170)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
```

### Filter to refresh user data on every request

```
@Component
@Order(UpdateAuthFilter.ORDER_AFTER_SPRING_SESSION)
@Slf4j
public class UpdateAuthFilter extends OncePerRequestFilter
{
    public static final int ORDER_AFTER_SPRING_SESSION = -2147483597;

    @Override
    protected void doFilterInternal(HttpServletRequest httpServletRequest,
        HttpServletResponse httpServletResponse, FilterChain filterChain)
        throws ServletException, IOException
    {
        HttpSession session = httpServletRequest.getSession();

        if (session != null)
        {
            SecurityContextImpl securityContextImpl = (SecurityContextImpl) session
                .getAttribute("SPRING_SECURITY_CONTEXT");
            if (securityContextImpl != null)
            {
                Authentication authentication = securityContextImpl.getAuthentication();
                try
                {
                    UserDetails userDetails = updateUserDetails(authentication.getPrincipal());

                    // Create a new Authentication object, Authentications are immutable.
                    UsernamePasswordAuthenticationToken newAuthentication =
                        new UsernamePasswordAuthenticationToken(userDetails,
                            authentication.getCredentials(), userDetails.getAuthorities());

                    SecurityContextHolder.getContext().setAuthentication(newAuthentication);
                    session.setAttribute("SPRING_SECURITY_CONTEXT", newAuthentication);
                } catch (UsernameNotFoundException e)
                {
                    // invalidate the session if the user could not be found
                    session.invalidate();
                }
            } else
            {
                //invalidate the session if the user could not be found
                session.invalidate();
            }
        }

        filterChain.doFilter(httpServletRequest, httpServletResponse);
    }

    private UserDetails updateUserDetails(Object principal)
    {
     ....  fetch user from db and build a new user details
    }
}
```

**Comment by vpavic** [comment]
Thanks for the report @alterhu2020.

It appears you're missing a critical part of your `ObjectMapper` configuration, please take a closer look at [this part](https://github.com/spring-projects/spring-session/blob/master/samples/boot/redis-json/src/main/java/sample/config/SessionConfig.java#L48) of `SessionConfig` from our Redis JSON sample. Can you double check that?

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.

**Comment by sarathpetec** [comment]
I would appreciate it if you could post the path again to this end point, as it is not reachable. [Path](https://github.com/spring-projects/spring-session/blob/master/samples/boot/redis-json/src/main/java/sample/config/SessionConfig.java#L48)

**Comment by RickHeadle** [comment]
> I would appreciate it if you could post the path again to this end point, as it is not reachable. [Path](https://github.com/spring-projects/spring-session/blob/master/samples/boot/redis-json/src/main/java/sample/config/SessionConfig.java#L48)

I believe the new link should be this one: [Path](https://github.com/spring-projects/spring-session/blob/429e77f3048669e7a0475b8e9f09258b3f0f1028/spring-session-samples/spring-session-sample-boot-redis-json/src/main/java/sample/config/SessionConfig.java)
