### ISSUE TITLE
hazelcast client/server topology classnotfound

### ISSUE THREAD

**Issue by krm1312** [spring-projects/spring-session#964]
Sample app:

https://github.com/krm1312/hzss

Start a local instance of hazelcast standalone.  Then try to start above spring boot app.  Fails immediately with the following:

```
Caused by: java.lang.ClassNotFoundException: org.springframework.session.hazelcast.PrincipalNameExtractor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_112]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_112]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_112]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_112]
	at com.hazelcast.query.impl.getters.ExtractorHelper.instantiateExtractorWithClassForName(ExtractorHelper.java:84) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.query.impl.getters.ExtractorHelper.instantiateExtractor(ExtractorHelper.java:59) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.query.impl.getters.ExtractorHelper.instantiateExtractors(ExtractorHelper.java:41) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.query.impl.getters.Extractors.<init>(Extractors.java:54) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:135) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:185) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:181) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:93) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:280) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.PartitionContainer.createRecordStore(PartitionContainer.java:107) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.PartitionContainer.access$000(PartitionContainer.java:45) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.PartitionContainer$1.createNew(PartitionContainer.java:58) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.PartitionContainer$1.createNew(PartitionContainer.java:54) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:93) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.PartitionContainer.getRecordStore(PartitionContainer.java:171) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.operation.MapOperation.getRecordStoreOrNull(MapOperation.java:157) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.operation.MapOperation.innerBeforeRun(MapOperation.java:78) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.map.impl.operation.MapOperation.beforeRun(MapOperation.java:74) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:188) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120) ~[hazelcast-3.9.2.jar:3.9.2]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) ~[hazelcast-3.9.2.jar:3.9.2]
```

I'm not sure if this is supposed to work, though, some old issues here imply that the client/server hazelcast topology was supported.

**Comment by krm1312** [comment]
It appears to be unsupported unless all classes of objects that could potentially be stored in the session are in the server side classpath.  I managed to get past the above exception by creating another app that embeds hazelcast (the server) and adding spring-session related dependencies/classes.  It then fails on CsrfToken (fixed by adding spring-security) and then on our application classes.

**Comment by vpavic** [comment]
Thanks for the report @krm1312.

The client-server topology is supported by Spring Session. Note that for some functionalities, such as `ValueExtractor` we're using to implement `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue`, Hazelcast requires the presence of classes on the server.

So you need to include the Spring Session classes on your Hazelcast server. However, if you actually don't intend to use `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue` then this is not needed - you just need to omit [this part](https://github.com/krm1312/hzss/blob/master/src/main/java/foo/bar/hzss/HzssConfig.java#L45-L53) of your configuration.

We'll look into the possibilities of improving this, if possible.

In the meanwhile, if you're willing to experiment, Hazelcast 3.9 introduced a new feature that allows client code deployment to the cluster. You can learn more about it [here](http://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#client-user-code-deployment-beta).

**Comment by krm1312** [comment]
I did try for a bit to get the code deployment functionality working and was not successful.  Is there any performance impact by removing the ValueExtractor and IndexConfig if the application code does not use findByIndexNameAndIndexValue?

Thanks for your reply.

**Comment by vpavic** [comment]
> I did try for a bit to get the code deployment functionality working and was not successful.

I'd suggest to look for support on Hazelcast's issue tracker. If you do so, feel free to update this issue with reference.

> Is there any performance impact by removing the ValueExtractor and IndexConfig if the application code does not use findByIndexNameAndIndexValue?

There's no performance impact. Those two are only there to provide `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue` capability.

**Comment by vpavic** [comment]
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.
